import Dexie, { type EntityTable } from 'dexie'

export interface Car {
  id: string
  make: string
  model: string
  year: number
  engine?: string
  vin?: string
  odometer: number
  createdAt: string
  updatedAt: string
}

export interface Setting {
  key: string
  value: string
}

export const ENTRY_CATEGORIES = [
  'fuel',
  'service',
  'repair',
  'tyres',
  'insurance',
  'other',
] as const

export type EntryCategory = (typeof ENTRY_CATEGORIES)[number]

// One line from a receipt/invoice: what was bought or done, and what it cost
// including DPH (VAT). Kept as a breakdown — `cost` on the entry stays the
// authoritative total, because a receipt total can include discounts that no
// single line shows.
export interface LineItem {
  name: string
  price: number
}

export interface LogEntry {
  id: string
  carId: string
  date: string // YYYY-MM-DD
  odometer: number
  cost: number
  category: EntryCategory
  notes?: string
  // Who was paid — the shop/garage/station from the receipt or entered by hand.
  company?: string
  // Itemised breakdown from the receipt (name + price incl. DPH). Not indexed,
  // so no Dexie version bump is needed to carry it.
  items?: LineItem[]
  // Fuel-only fields. fullTank matters: economy math is only valid on
  // full-to-full intervals, so partial fills must be marked.
  litres?: number
  pricePerLitre?: number
  fullTank?: boolean
  // Set on auto-saved scanned entries until the owner confirms them
  needsReview?: boolean
  createdAt: string
  updatedAt: string
}

export interface Reminder {
  id: string
  carId: string
  title: string
  // At least one of dueDate / dueOdometer is always set (validated on entry)
  dueDate?: string // YYYY-MM-DD
  dueOdometer?: number
  // Recurrence: completing rolls the next occurrence forward from completion
  repeatKm?: number
  repeatMonths?: number
  notes?: string
  completedAt?: string
  // Set on reminders generated by the tyre module: the set to be fitted
  tyreSetId?: string
  createdAt: string
  updatedAt: string
}

export const TYRE_SEASONS = ['summer', 'winter', 'all-season'] as const

export type TyreSeason = (typeof TYRE_SEASONS)[number]

export interface TreadReading {
  date: string // YYYY-MM-DD
  mm: number
}

// One stretch of time the set spent on the car. The open period (no toDate)
// belongs to the currently fitted set; km-on-set is derived from these.
export interface FittedPeriod {
  fromDate: string
  fromOdo: number
  toDate?: string
  toOdo?: number
}

export interface TyreSet {
  id: string
  carId: string
  season: TyreSeason
  brand?: string
  model?: string
  size?: string // '225/40 R19'
  status: 'fitted' | 'stored'
  // 1-12: the month this set normally goes ON. Swap reminders anchor to it
  // so a late swap doesn't drift the next one out of season.
  swapMonth?: number
  purchaseDate?: string
  purchaseOdometer?: number
  storageLocation?: string
  notes?: string
  treadReadings: TreadReading[]
  fittedPeriods: FittedPeriod[]
  createdAt: string
  updatedAt: string
}

export interface Attachment {
  id: string
  entryId: string
  // Denormalised so export and per-car cleanup don't need to join via entries
  carId: string
  name: string
  mime: string // 'image/jpeg' | 'application/pdf'
  size: number // byte length, AFTER downscaling
  // Raw bytes, not a Blob: WebKit has a long history of bugs storing Blobs in
  // IndexedDB, and this app is iOS-first. A Blob is built at display time.
  bytes: ArrayBuffer
  createdAt: string
}

export interface ChatMessage {
  id: string
  carId: string
  role: 'user' | 'assistant'
  text: string
  createdAt: string
}

export const db = new Dexie('garagebook') as Dexie & {
  cars: EntityTable<Car, 'id'>
  settings: EntityTable<Setting, 'key'>
  entries: EntityTable<LogEntry, 'id'>
  reminders: EntityTable<Reminder, 'id'>
  chatMessages: EntityTable<ChatMessage, 'id'>
  tyreSets: EntityTable<TyreSet, 'id'>
  attachments: EntityTable<Attachment, 'id'>
}

db.version(1).stores({
  // Only fields we query/sort by need indexing; the rest live on the object.
  cars: 'id, make, createdAt',
})

db.version(2).stores({
  settings: 'key',
})

db.version(3).stores({
  entries: 'id, carId, [carId+date]',
})

db.version(4).stores({
  reminders: 'id, carId',
})

db.version(5).stores({
  chatMessages: 'id, carId',
})

db.version(6).stores({
  tyreSets: 'id, carId',
})

// Blobs live in their own store, never on LogEntry: entriesForCar feeds the
// Logbook, Insights, car detail and the AI context builder, and none of them
// want megabytes of image data dragged along.
db.version(7).stores({
  attachments: 'id, entryId, carId',
})
